Repository Property-Search-Engine/admin-front, pull requests merged in 2021-02, with the labels that each got.

#19 Feat/modal form
  .eslintcache
  public/assets/icons/filter.svg
  public/assets/icons/m2.svg
  public/assets/icons/tagblue.svg
  src/components/Dashboard/Dashboard.js
  src/components/common/Inputs/CheckInput.js
  src/components/common/Inputs/DateInput.js
  src/components/common/Inputs/Input.scss
  src/components/common/Inputs/NumberInput.js
  src/components/common/Inputs/RadioCheckInputs.scss
  src/components/common/Inputs/RadioInputs.js
  src/components/common/Inputs/TextInput.js
  src/components/common/Modal/Modal.js
  src/components/common/Modal/Modal.scss
  src/components/common/ModalForm/ModalForm.js
  src/components/common/ModalForm/ModalForm.scss
  src/components/common/ModalForm/ModalForm.test.js
  src/styles/main.scss
  src/styles/partials/_mixings.scss
  src/styles/partials/_variables.scss
  src/utils/helpers.js
Labels: enhancement

#24 Feature/header component
  public/assets/icons/magnifying-glass.svg
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.scss
  src/components/common/Header/Header.js
  src/components/common/Header/Header.scss
  src/components/common/NavItem/NavItem.js
  src/components/common/Sidebar/Sidebar.js
  src/components/common/Sidebar/Sidebar.scss
  src/styles/main.scss
Labels: enhancement

#27 Feature/header component
  public/assets/icons/arrow-down.svg
  public/assets/icons/bell.svg
  public/assets/testing_images/IMG_7429.jpg
  src/components/common/AdminSettings/AdminSettings.js
  src/components/common/AdminSettings/AdminSettings.scss
  src/components/common/Header/Header.js
  src/components/common/Header/Header.scss
  src/components/common/Notification/Notification.js
  src/components/common/Notification/Notification.scss
  src/components/common/Sidebar/Sidebar.scss
  src/styles/main.scss
  src/styles/partials/_variables.scss
Labels: enhancement

#28 Bug fix/value blocking modal form
  src/components/common/Inputs/CheckInput.js
  src/components/common/Inputs/DateInput.js
  src/components/common/Inputs/NumberInput.js
  src/components/common/Inputs/RadioInputs.js
  src/components/common/Inputs/SelectInput.js
  src/components/common/Inputs/TextInput.js
  src/components/common/ModalForm/ModalForm.js
  src/utils/helpers.js
Labels: bug

#30 Feature/image carousel
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.scss
  src/components/Listing/ImageCarousel/ImageCarousel.js
  src/components/Listing/ImageCarousel/ImageCarousel.scss
  src/components/Listing/Listing.js
  src/components/Listing/ListingContainer/ListContainer.js
  src/components/Listing/ListingContainer/ListContainer.scss
  src/components/Listing/ListingRowContainer/ListingRowContainer.js
  src/components/Listing/Thead/Thead.js
  src/styles/main.scss
Labels: enhancement

#33 Feature/home details page
  public/assets/icons/sold-active.svg
  src/App.js
  src/components/ExtraPropertyDetails/ExtraPropertyDetails.js
  src/components/ExtraPropertyDetails/ExtraPropertyDetails.scss
  src/components/Listing/ListingContainer/ListContainer.js
  src/components/Listing/ListingRowContainer/ListingRowContainer.js
  src/components/PropertyDetails/PropertyDetails.js
  src/components/PropertyDetails/PropertyDetails.scss
  src/components/common/Notification/Notification.js
  src/styles/main.scss
  src/utils/helpers.js
  src/utils/routes.js
Labels: enhancement

#34 Feature/dynamic carousel
  src/components/Listing/ImageCarousel/ImageCarousel.js
  src/components/Listing/ImageCarousel/ImageCarousel.scss
  src/components/PropertyDetails/PropertyDetails.js
Labels: enhancement

#35 Complete error 404 landing page
  public/assets/images/404_error_ufo.png
  src/App.js
  src/components/Error/Error.js
  src/components/Error/Error.scss
  src/styles/main.scss
  src/utils/routes.js
Labels: enhancement

#41 Create Settings and Form to add new admin
  src/App.js
  src/components/pages/Settings/NewAdminForm/NewAdminForm.js
  src/components/pages/Settings/NewAdminForm/NewAdminForm.scss
  src/components/pages/Settings/Settings.js
  src/components/pages/Settings/Settings.scss
  src/styles/main.scss
Labels: enhancement

#40 Create spinner
  src/components/common/LoadingSpinner/LoadingSpinner.js
  src/components/common/LoadingSpinner/LoadingSpinner.scss
  src/styles/main.scss
Labels: enhancement

#47 Work login logic and data gathering from back-end
  src/components/pages/Login/Login.js
  src/components/pages/PropertyDetails/PropertyDetails.js
  src/redux/user/user-actions.js
  src/redux/user/user-reducer.js
  src/utils/endpoints.js
Labels: enhancement

#48 Connect redux for logginOut
  src/components/common/AdminSettings/AdminSettings.js
  src/components/common/Header/Header.js
  src/components/pages/Login/Login.js
  src/redux/containers/pages/AdminSettingsContainer.js
Labels: enhancement

#49 Change new Admin form and added validation
  package-lock.json
  package.json
  src/components/common/Header/Header.scss
  src/components/pages/Settings/NewAdminForm/NewAdminForm.js
  src/components/pages/Settings/NewAdminForm/NewAdminForm.scss
Labels: enhancement

#52 Feature/create redux entities
  src/components/common/NavItem/NavItem.js
  src/components/pages/Settings/NewAdminForm/NewAdminForm.js
  src/components/pages/Settings/Settings.js
  src/redux/containers/components/FiltersContainer.js
  src/redux/containers/components/ListContainer.js
  src/redux/containers/components/NewAdminFormContainer.js
  src/redux/containers/pages/SettingsContainer.js
  src/redux/employees/employees-actions.js
  src/redux/employees/employees-reducer.js
  src/redux/employees/employees-types.js
  src/redux/properties/properties-actions.js
  src/redux/properties/properties-reducer.js
  src/redux/root-reducer.js
  src/redux/user/user-actions.js
  src/redux/user/user-reducer.js
  src/redux/user/user-types.js
  src/utils/endpoints.js
  src/utils/helpers.js
Labels: bug, enhancement

#54 Feature/upload property image
  src/components/common/AdminSettings/AdminSettings.js
  src/components/common/ModalForm/ModalForm.js
  src/components/pages/Listing/List/List.js
  src/firebase/firebase.js
  src/redux/containers/components/ModalFormContainer.js
  src/redux/containers/pages/AdminSettingsContainer.js
  src/redux/properties/properties-actions.js
  src/redux/properties/properties-reducer.js
  src/utils/endpoints.js
Labels: enhancement

#55 Feature/filters to redux
  src/App.js
  src/components/common/AdminSettings/AdminSettings.js
  src/components/common/Inputs/CheckInput.js
  src/components/common/LoadingSpinner/LoadingSpinner.js
  src/components/common/ModalForm/ModalForm.js
  src/components/pages/Listing/Filters/Filters.js
  src/components/pages/Listing/List/List.js
  src/components/pages/Listing/Listing.js
  src/components/pages/Listing/ListingRowContainer/ListingRowContainer.js
  src/components/pages/PropertyDetails/PropertyDetails.js
  src/redux/containers/components/ListContainer.js
  src/redux/containers/pages/ListingContainer.js
  src/redux/containers/pages/PropertyDetailsContainer.js
  src/redux/employees/employees-actions.js
  src/redux/properties/properties-actions.js
  src/redux/properties/properties-reducer.js
  src/redux/properties/properties-types.js
  src/redux/user/user-actions.js
  src/utils/endpoints.js
  src/utils/helpers.js
  src/utils/routes.js
Labels: bug, enhancement
